const levels=[
  {title:'Fundamentos de la nube',description:'Las palabras que necesitas para comenzar.',takeaway:'La nube entrega tecnología por Internet. Los recursos viven en centros de datos, se organizan por regiones y normalmente se paga según el uso.',pairs:[
    ['Computación en la nube','Uso de servidores, almacenamiento y programas a través de Internet, sin tener que comprar todos los equipos físicos.','Ejemplo: guardar una copia de seguridad en Azure en lugar de comprar otro disco.'],
    ['Recurso','Cada elemento que creas o utilizas dentro de una plataforma en la nube.','Una máquina virtual, una base de datos y una red son recursos.'],
    ['Centro de datos','Edificio preparado con servidores, energía, refrigeración, redes y seguridad física.','Los proveedores operan muchos centros de datos alrededor del mundo.'],
    ['Región','Zona geográfica donde un proveedor reúne uno o varios centros de datos.','Al crear un recurso eliges una región cercana o adecuada para tus datos.'],
    ['Disponibilidad','Capacidad de un servicio para permanecer funcionando y accesible.','Una alta disponibilidad reduce el tiempo que una aplicación está fuera de servicio.'],
    ['Pago por uso','Modelo en el que el costo depende de los recursos y del tiempo realmente consumidos.','Una VM encendida durante dos horas consume menos que la misma VM encendida todo el mes.']
  ]},
  {title:'Ventajas de la nube',description:'Cómo cambia la capacidad cuando un proyecto crece.',takeaway:'La nube permite ajustar capacidad, recuperarse de fallos y atender usuarios desde diferentes lugares. Cada ventaja necesita una configuración correcta.',pairs:[
    ['Escalabilidad','Capacidad de aumentar o reducir recursos para atender más o menos trabajo.','Agregar otra instancia de una aplicación cuando llegan más visitantes.'],
    ['Elasticidad','Ajuste rápido o automático de recursos cuando cambia la demanda.','Aumentar capacidad durante una matrícula y reducirla cuando termina.'],
    ['Tolerancia a fallos','Diseño que permite continuar funcionando aunque un componente falle.','Si un servidor falla, otro puede atender las solicitudes.'],
    ['Alta disponibilidad','Uso de varias partes o ubicaciones para reducir interrupciones del servicio.','Distribuir una aplicación entre zonas de disponibilidad.'],
    ['Copia de seguridad','Copia separada de los datos que permite recuperarlos después de una pérdida.','Guardar una copia diaria de la base de datos.'],
    ['Latencia','Tiempo que tarda la información en viajar entre el usuario y el servicio.','Una región cercana normalmente responde más rápido que una muy lejana.']
  ]},
  {title:'IaaS, PaaS y SaaS',description:'Cuánto administra el proveedor y cuánto administras tú.',takeaway:'IaaS ofrece más control y más trabajo. PaaS permite concentrarse en la aplicación. SaaS entrega un programa terminado. En todos los modelos debes proteger datos e identidades.',pairs:[
    ['IaaS','Alquiler de infraestructura como máquinas, redes y discos; tú administras el sistema operativo y las aplicaciones.','Azure Virtual Machines y Amazon EC2 son ejemplos.'],
    ['PaaS','Plataforma lista para publicar código o datos sin administrar el sistema operativo.','Azure App Service y Google App Engine son ejemplos.'],
    ['SaaS','Aplicación completa que utilizas desde Internet; el proveedor administra casi toda la tecnología.','Microsoft 365 y Google Workspace son ejemplos.'],
    ['Sin servidor','El proveedor asigna automáticamente la infraestructura y tu código se ejecuta cuando ocurre un evento.','Azure Functions, AWS Lambda y Cloud Functions.'],
    ['Responsabilidad compartida','Reparto de tareas de seguridad entre el proveedor y el cliente.','El proveedor protege el edificio; tú proteges cuentas, datos y configuración.'],
    ['Entorno local','Servidores y equipos que una organización mantiene en sus propias instalaciones.','También se conoce como on-premises.']
  ]},
  {title:'Tipos de nube',description:'Dónde se ejecutan los servicios y cómo se combinan.',takeaway:'Pública, privada e híbrida describen dónde y para quién funciona la infraestructura. Multinube significa usar más de un proveedor; no es lo mismo que nube híbrida.',pairs:[
    ['Nube pública','Infraestructura operada por un proveedor que ofrece servicios a muchos clientes a través de Internet.','Azure, AWS y Google Cloud ofrecen nube pública.'],
    ['Nube privada','Infraestructura de nube dedicada a una sola organización.','Una empresa puede operar su nube privada en su propio centro de datos.'],
    ['Nube híbrida','Combinación conectada de recursos locales o privados con una nube pública.','Datos sensibles permanecen localmente y la web funciona en Azure.'],
    ['Multinube','Uso de servicios de dos o más proveedores de nube.','Una empresa usa Azure para identidad y AWS para otra aplicación.'],
    ['Computación perimetral','Procesamiento de datos cerca del lugar donde se producen para responder más rápido.','Una fábrica procesa datos cerca de sus sensores.'],
    ['Migración a la nube','Proceso de trasladar aplicaciones, datos o servicios desde otro entorno hacia la nube.','Mover una base de datos local a un servicio administrado.']
  ]},
  {title:'Proveedores de nube',description:'Quién ofrece las principales plataformas.',takeaway:'Microsoft Azure, AWS y Google Cloud son proveedores globales muy conocidos. También existen Oracle, IBM y Alibaba. La elección depende del proyecto, no solo de popularidad.',pairs:[
    ['Microsoft Azure','Plataforma de nube de Microsoft, integrada con tecnologías como Windows, Microsoft 365 y Microsoft Entra.','Ofrece Azure Virtual Machines, Blob Storage, App Service y Azure SQL.'],
    ['Amazon Web Services (AWS)','Plataforma de nube de Amazon y una de las primeras en ofrecer infraestructura pública a gran escala.','Entre sus servicios están EC2, S3, RDS y Lambda.'],
    ['Google Cloud','Plataforma de nube de Google, conocida por datos, inteligencia artificial, Kubernetes y su red global.','Ofrece Compute Engine, Cloud Storage y Cloud SQL.'],
    ['Oracle Cloud (OCI)','Plataforma de Oracle orientada, entre otros usos, a bases de datos y aplicaciones empresariales.','Incluye Oracle Database y servicios de cómputo.'],
    ['IBM Cloud','Plataforma de IBM con servicios de nube híbrida, empresas e inteligencia artificial.','Se relaciona con tecnologías empresariales y Red Hat OpenShift.'],
    ['Alibaba Cloud','Plataforma de nube de Alibaba con presencia importante en Asia y servicios globales.','Ofrece cómputo, almacenamiento, bases de datos y redes.']
  ]},
  {title:'Familias de servicios',description:'El problema que resuelve cada grupo de herramientas.',takeaway:'Los nombres cambian entre proveedores, pero las necesidades se repiten: ejecutar, guardar, conectar, organizar datos, controlar accesos y observar.',pairs:[
    ['Cómputo','Servicios que proporcionan capacidad para ejecutar sistemas, aplicaciones o código.','Azure VM, Amazon EC2 y Compute Engine realizan tareas de cómputo.'],
    ['Almacenamiento de objetos','Servicio para guardar archivos como imágenes, videos, documentos y copias.','Azure Blob Storage, Amazon S3 y Google Cloud Storage.'],
    ['Redes','Servicios que conectan recursos y controlan cómo viaja el tráfico.','Azure Virtual Network, Amazon VPC y Google VPC.'],
    ['Base de datos administrada','Motor de datos cuyo servidor, parches y copias son gestionados en gran parte por el proveedor.','Azure SQL Database, Amazon RDS y Google Cloud SQL.'],
    ['Identidad y acceso','Servicios que reconocen usuarios y determinan sus permisos.','Microsoft Entra ID, AWS IAM y Cloud IAM.'],
    ['Supervisión','Herramientas que reúnen métricas, registros y alertas para conocer el estado de los recursos.','Azure Monitor, Amazon CloudWatch y Google Cloud Monitoring.']
  ]},
  {title:'Seguridad y costos',description:'Hábitos para usar la nube de manera responsable.',takeaway:'Una nube segura necesita identidades protegidas, permisos mínimos, cifrado, reglas de red, presupuestos y limpieza. El proveedor no puede corregir una mala configuración del usuario.',pairs:[
    ['MFA','Verificación que solicita dos o más pruebas para entrar a una cuenta.','Contraseña más código del teléfono.'],
    ['Mínimo privilegio','Regla de entregar solamente los permisos necesarios y durante el tiempo necesario.','Un observador recibe Lector, no Propietario.'],
    ['Cifrado','Transformación de los datos para que no puedan leerse sin la clave correcta.','HTTPS cifra datos en tránsito; el almacenamiento puede cifrar datos guardados.'],
    ['Firewall','Conjunto de reglas que permite o bloquea conexiones de red.','Permitir HTTPS y bloquear puertos administrativos desde Internet.'],
    ['Presupuesto','Herramienta que compara el gasto con una cantidad y envía alertas; no apaga recursos.','Avisar al correo cuando el consumo llegue al 80 %.'],
    ['FinOps','Práctica de colaborar para entender, controlar y optimizar los costos de la nube.','Etiquetar recursos, revisar consumos y eliminar lo que no se utiliza.']
  ]}
];

const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
const screens={start:$('#startScreen'),picker:$('#levelPicker'),play:$('#playScreen'),complete:$('#levelComplete'),final:$('#finalScreen')};
let mode='learn',levelIndex=0,score=0,levelStartScore=0,streak=0,bestStreak=0,attempts=0,matched=new Set(),selected=null,timerId=null,timeLeft=75,sound=true,wrongTerms=new Set();
let completed=JSON.parse(localStorage.getItem('cloud-game-completed')||'[]');
let globalReview=new Set(JSON.parse(localStorage.getItem('cloud-game-review')||'[]'));

function shuffle(list){return [...list].sort(()=>Math.random()-.5)}
function show(name){Object.values(screens).forEach(s=>s.hidden=true);screens[name].hidden=false;scrollTo({top:0,behavior:'smooth'})}
function tone(ok){if(!sound)return;try{const c=new (window.AudioContext||window.webkitAudioContext)(),o=c.createOscillator(),g=c.createGain();o.connect(g);g.connect(c.destination);o.frequency.value=ok?660:180;g.gain.value=.04;o.start();o.stop(c.currentTime+.11)}catch{}}
function updateSaved(){const best=Number(localStorage.getItem('cloud-game-best')||0);$('#savedMessage').textContent=best?`Tu mejor puntuación guardada es ${best} puntos.`:'Tu progreso se guardará en este navegador.'}

function renderPicker(){const grid=$('#levelGrid');grid.innerHTML='';levels.forEach((level,i)=>{const done=completed.includes(i);const b=document.createElement('button');b.className='level-card';b.innerHTML=`<span class="number">${String(i+1).padStart(2,'0')}</span><h3>${level.title}</h3><p>${level.description}</p><small>${done?'✓ Completado':'6 relaciones'}</small>`;b.addEventListener('click',()=>startLevel(i));grid.append(b)})}
function startLevel(index){clearInterval(timerId);levelIndex=index;levelStartScore=score;streak=0;bestStreak=0;attempts=0;matched=new Set();selected=null;wrongTerms=new Set();timeLeft=75;const level=levels[index];$('#levelCounter').textContent=`NIVEL ${index+1} DE ${levels.length}`;$('#levelTitle').textContent=level.title;$('#levelDescription').textContent=level.description;$('#timerBox').hidden=mode==='learn';$('#timer').textContent=mode==='learn'?'∞':timeLeft;renderBoard();updateStats();show('play');$('#feedback').className='feedback';$('#feedback').innerHTML='<span>Selecciona un concepto para comenzar.</span>';if(mode==='challenge')timerId=setInterval(tick,1000)}
function renderBoard(){const level=levels[levelIndex],terms=$('#terms'),defs=$('#definitions');terms.innerHTML='';defs.innerHTML='';shuffle(level.pairs.map((p,i)=>({p,i}))).forEach(({p,i})=>{const b=document.createElement('button');b.className='card';b.dataset.id=i;b.textContent=p[0];b.addEventListener('click',()=>selectTerm(b,i));terms.append(b)});shuffle(level.pairs.map((p,i)=>({p,i}))).forEach(({p,i})=>{const b=document.createElement('button');b.className='card';b.dataset.id=i;b.textContent=p[1];b.addEventListener('click',()=>selectDefinition(b,i));defs.append(b)})}
function selectTerm(button,id){if(matched.has(id))return;$$('.terms .card').forEach(x=>x.classList.remove('selected'));button.classList.add('selected');selected=id;const pair=levels[levelIndex].pairs[id];$('#feedback').className='feedback';$('#feedback').innerHTML=`Busca la explicación de <b>${pair[0]}</b>.`}
function selectDefinition(button,id){if(selected===null){$('#feedback').className='feedback incorrect';$('#feedback').textContent='Primero selecciona un concepto de la columna izquierda.';tone(false);return}attempts++;const termButton=$(`.terms .card[data-id="${selected}"]`),chosen=selected;if(id===chosen){matched.add(chosen);streak++;bestStreak=Math.max(bestStreak,streak);const gain=20+Math.min(streak*2,10);score+=gain;termButton.classList.remove('selected');termButton.classList.add('matched');termButton.disabled=true;button.classList.add('matched');button.disabled=true;const p=levels[levelIndex].pairs[chosen];$('#feedback').className='feedback correct';$('#feedback').innerHTML=`<b>¡Correcto! +${gain}</b> ${p[2]}`;selected=null;tone(true);updateStats();if(matched.size===levels[levelIndex].pairs.length)setTimeout(completeLevel,700)}else{streak=0;wrongTerms.add(levels[levelIndex].pairs[chosen][0]);globalReview.add(levels[levelIndex].pairs[chosen][0]);termButton.classList.add('wrong');button.classList.add('wrong');setTimeout(()=>{termButton.classList.remove('wrong');button.classList.remove('wrong')},450);$('#feedback').className='feedback incorrect';$('#feedback').innerHTML='<b>Aún no.</b> Lee nuevamente la explicación y prueba otra tarjeta. No pierdes el concepto seleccionado.';tone(false);updateStats()}}
function updateStats(){$('#score').textContent=score;$('#streak').textContent=streak;$('#attempts').textContent=attempts;$('#levelProgress').style.width=`${matched.size/6*100}%`}
function tick(){timeLeft--;$('#timer').textContent=timeLeft;if(timeLeft<=10)$('#timerBox').style.color='#d64848';if(timeLeft<=0){clearInterval(timerId);$('#timer').textContent='0';$('#feedback').className='feedback incorrect';$('#feedback').innerHTML='<b>Se terminó el tiempo del reto.</b> Puedes completar las relaciones sin presión; ya no hay límite.'}}
function completeLevel(){clearInterval(timerId);if(!completed.includes(levelIndex))completed.push(levelIndex);localStorage.setItem('cloud-game-completed',JSON.stringify(completed));localStorage.setItem('cloud-game-review',JSON.stringify([...globalReview]));const levelScore=score-levelStartScore,accuracy=Math.round(6/Math.max(attempts,6)*100);$('#completeTitle').textContent=accuracy===100?'¡Nivel perfecto!':'¡Nivel superado!';$('#completeText').textContent=`Relacionaste los 6 conceptos de “${levels[levelIndex].title}”.`;$('#levelScore').textContent=levelScore;$('#accuracy').textContent=`${accuracy}%`;$('#bestStreak').textContent=bestStreak;$('#learned').innerHTML=`<h3>Lo más importante</h3><p>${levels[levelIndex].takeaway}</p>`;$('#nextBtn').textContent=levelIndex===levels.length-1?'Ver resultado final →':'Siguiente nivel →';show('complete')}
function finish(){const best=Math.max(score,Number(localStorage.getItem('cloud-game-best')||0));localStorage.setItem('cloud-game-best',best);$('#finalScore').textContent=score;$('#rank').textContent=score>=950?'Arquitecto de la nube':score>=750?'Especialista de la nube':score>=550?'Explorador de la nube':'Aprendiz de la nube';const mastery=$('#mastery');mastery.innerHTML='';levels.forEach((l,i)=>{const d=document.createElement('div');d.textContent=`${completed.includes(i)?'✓':'○'} ${l.title}`;mastery.append(d)});const list=$('#reviewList');list.innerHTML='';if(globalReview.size){[...globalReview].forEach(x=>{const s=document.createElement('span');s.textContent=x;list.append(s)});$('#reviewBox').hidden=false}else $('#reviewBox').hidden=true;show('final')}

$$('.mode').forEach(b=>b.addEventListener('click',()=>{$$('.mode').forEach(x=>x.classList.remove('active'));b.classList.add('active');mode=b.dataset.mode}));
$('#startBtn').addEventListener('click',()=>startLevel(0));$('#levelsBtn').addEventListener('click',()=>{renderPicker();show('picker')});$('#closePicker').addEventListener('click',()=>show('start'));$('#hintBtn').addEventListener('click',()=>{if(selected===null){$('#feedback').className='feedback incorrect';$('#feedback').textContent='Selecciona primero un concepto para poder usar la pista.';return}score=Math.max(0,score-10);wrongTerms.add(levels[levelIndex].pairs[selected][0]);globalReview.add(levels[levelIndex].pairs[selected][0]);const target=$(`.definitions .card[data-id="${selected}"]`);target.classList.add('hint');setTimeout(()=>target.classList.remove('hint'),1600);$('#feedback').className='feedback';$('#feedback').textContent='La respuesta correcta está iluminada durante un momento.';updateStats()});
$('#resetLevelBtn').addEventListener('click',()=>{renderBoard();selected=null;matched.forEach(id=>{const t=$(`.terms .card[data-id="${id}"]`),d=$(`.definitions .card[data-id="${id}"]`);if(t){t.classList.add('matched');t.disabled=true}if(d){d.classList.add('matched');d.disabled=true}})});$('#exitBtn').addEventListener('click',()=>{clearInterval(timerId);show('start')});$('#nextBtn').addEventListener('click',()=>levelIndex===levels.length-1?finish():startLevel(levelIndex+1));$('#repeatBtn').addEventListener('click',()=>{score=levelStartScore;startLevel(levelIndex)});$('#playAgainBtn').addEventListener('click',()=>{score=0;globalReview=new Set();startLevel(0)});$('#soundBtn').addEventListener('click',e=>{sound=!sound;e.currentTarget.textContent=`Sonido: ${sound?'sí':'no'}`;e.currentTarget.setAttribute('aria-pressed',String(sound))});
updateSaved();renderPicker();
